empleados = [
    {
        "FirstName" : "Anna",
        "LastName" :"Vaquero",
        "ReportsTo" : "Juan",
        "BirthDate" : "10/1/1926",
        "HireDate" : "3/5/2011",
        "Address" : "Rambla Catalunya, 18",
        "City" : "Zeanuri",
        "Province":"Bizkaia",
        "Country" : "Spain",
        "PostalCode" : "48401",
        "Phone" : 664946075,
        "Fax" : 5454545454,
        "Email" : "my6geogg3@earthling.net"
    },
    {
        "FirstName" : "Virginia",
        "LastName" :"Cerezo",
        "ReportsTo" : "Juan",
        "BirthDate" : "19/5/1961",
        "HireDate" : "4/5/2010",
        "Address" : "Camino Iglesia, 55",
        "City" : "Quintanaélez",
        "Province":"Burgos",
        "Country" : "Spain",
        "PostalCode" : "09381",
        "Phone" : 711020899,
        "Fax" : 5454545454,
        "Email" : "a2bf7l6uv@earthling.net"
    },  
    {
        "FirstName" : "Emma",
        "LastName" :"Ariza",
        "ReportsTo" : "Juan",
        "BirthDate" : "16/11/1925",
        "HireDate" : "3/5/2011",
        "Address" : "Avenida Iglesia, 29",
        "City" : "Matallana de Toría",
        "Province":"León",
        "Country" : "Spain",
        "PostalCode" : "24170",
        "Phone" : 734120106,
        "Fax" : 5454545454,
        "Email" : "t022rx9lap@lycos.nl"
    },
    {
        "FirstName" : "Emilia",
        "LastName" :"Real",
        "ReportsTo" : "Juan",
        "BirthDate" : "4/8/1948",
        "HireDate" : "3/5/2011",
        "Address" : "Cuesta Real, 44",
        "City" : "Cortes y Graena",
        "Province":"Granada",
        "Country" : "Spain",
        "PostalCode" : "18372",
        "Phone" : 768870004,
        "Fax" : 5454545454,
        "Email" : "0bg4lazgf@blu.it"
    },
    {
        "FirstName" : "Eugenio",
        "LastName" :"Lafuente",
        "ReportsTo" : "Juan",
        "BirthDate" : "25/2/1946",
        "HireDate" : "3/5/2008",
        "Address" : "Camino Horno, 50",
        "City" : "Castilleja de Guzmán",
        "Province":"Sevilla",
        "Country" : "Spain",
        "PostalCode" : "41746",
        "Phone" : 694732020,
        "Fax" : 5454545454,
        "Email" : "wfg5qi85a3@writeme.com"
    }
]